// DO NOT EDIT THIS FILE DIRECTLY
// This file was auto generated from the file test.cpp.j2 using the generate.py script

#include <iostream>

#include <mongocxx/client.hpp>
#include <mongocxx/instance.hpp>

int main(void) {
    mongocxx::instance inst{};
    std::cout << "mongo-cxx-driver version: " << MONGOCXX_VERSION_STRING << std::endl;
    std::cout << "THE alpine3.18 IMAGE WORKS!" << std::endl;
}
