var searchData=
[
  ['element_0',['Element',['../topic-bsoncxx-examples-bson-documents.html#access-a-document-element',1,'Access a Document Element'],['../topic-bsoncxx-examples-bson-errors.html#access-a-document-element-1',1,'Access a Document Element'],['../topic-bsoncxx-examples-bson-documents.html#access-an-array-element',1,'Access an Array Element'],['../topic-bsoncxx-examples-bson-errors.html#access-an-array-element-1',1,'Access an Array Element'],['../topic-bsoncxx-examples-bson-documents.html#from-a-document-element',1,'From a Document Element'],['../topic-bsoncxx-examples-bson-documents.html#from-an-array-element',1,'From an Array Element'],['../topic-bsoncxx-examples-bson-errors.html#from-an-invalid-element',1,'From an Invalid Element'],['../topic-bsoncxx-examples-bson-errors.html#invalid-element',1,'Invalid Element'],['../topic-bsoncxx-examples-bson-errors.html#invalid-element-1',1,'Invalid Element'],['../topic-bsoncxx-examples-bson-errors.html#missing-element',1,'Missing Element'],['../topic-bsoncxx-examples-bson-errors.html#missing-element-1',1,'Missing Element'],['../topic-bsoncxx-examples-bson-documents.html#query-an-element',1,'Query an Element'],['../topic-bsoncxx-examples-bson-errors.html#query-an-element-1',1,'Query an Element']]],
  ['enabled_1',['TLS Not Enabled',['../topic-mongocxx-examples-clients.html#tls-not-enabled',1,'']]],
  ['encryption_20options_2',['Encryption Options',['../topic-mongocxx-examples-clients.html#automatic-encryption-options',1,'Automatic Encryption Options'],['../topic-mongocxx-examples-clients.html#invalid-auto-encryption-options',1,'Invalid Auto Encryption Options']]],
  ['end_20iterators_3',['End Iterators',['../topic-bsoncxx-examples-bson-errors.html#end-iterators',1,'End Iterators'],['../topic-bsoncxx-examples-bson-errors.html#end-iterators-1',1,'End Iterators']]],
  ['error_20handling_4',['Error Handling',['../topic-bsoncxx-examples-bson-errors.html',1,'BSON Error Handling'],['../topic-bsoncxx-examples-decimal128.html#error-handling',1,'Error Handling'],['../topic-bsoncxx-examples-oid.html#error-handling-1',1,'Error Handling'],['../topic-mongocxx-examples-uri.html#error-handling-2',1,'Error Handling'],['../topic-mongocxx-examples-clients.html#error-handling-3',1,'Error Handling'],['../topic-mongocxx-examples-databases.html#error-handling-4',1,'Error Handling'],['../topic-mongocxx-examples-collections.html#error-handling-5',1,'Error Handling']]],
  ['errors_5',['Errors',['../topic-mongocxx-examples-instance.html#errors',1,'']]],
  ['estimate_20the_20number_20of_20documents_6',['Estimate the Number of Documents',['../topic-mongocxx-examples-collections.html#estimate-the-number-of-documents',1,'']]],
  ['example_7',['Example',['../topic-bsoncxx-examples-bson-documents.html#basic-example',1,'Basic Example'],['../topic-bsoncxx-examples-bson-documents.html#basic-example-1',1,'Basic Example'],['../topic-bsoncxx-examples-bson-documents.html#basic-example-2',1,'Basic Example'],['../topic-bsoncxx-examples-bson-documents.html#basic-example-3',1,'Basic Example'],['../topic-bsoncxx-examples-bson-documents.html#basic-example-4',1,'Basic Example'],['../topic-bsoncxx-examples-bson-documents.html#basic-example-5',1,'Basic Example']]],
  ['exception_8',['Exception',['../topic-mongocxx-examples-operation-exceptions.html#as-a-regular-exception',1,'As a Regular Exception'],['../topic-mongocxx-examples-operation-exceptions.html#as-an-operation-exception',1,'As an Operation Exception']]],
  ['exceptions_9',['Operation Exceptions',['../topic-mongocxx-examples-operation-exceptions.html',1,'topic-mongocxx-examples']]],
  ['execute_20a_20single_20bulk_20write_20operation_10',['Execute a Single Bulk Write Operation',['../topic-mongocxx-examples-collections.html#execute-a-single-bulk-write-operation',1,'']]],
  ['execute_20an_20aggregation_20operation_11',['Execute an Aggregation Operation',['../topic-mongocxx-examples-collections.html#execute-an-aggregation-operation',1,'']]],
  ['execute_20multiple_20bulk_20write_20operations_12',['Execute Multiple Bulk Write Operations',['../topic-mongocxx-examples-collections.html#execute-multiple-bulk-write-operations',1,'']]],
  ['exists_13',['Query a Collection Exists',['../topic-mongocxx-examples-databases.html#query-a-collection-exists',1,'']]],
  ['explanation_14',['Explanation',['../topic-bsoncxx-about.html',1,'Explanation'],['../topic-mongocxx-about.html',1,'Explanation']]],
  ['extended_20json_15',['Extended JSON',['../topic-bsoncxx-examples-bson-documents.html#with-extended-json',1,'With Extended JSON'],['../topic-bsoncxx-examples-bson-documents.html#with-extended-json-1',1,'With Extended JSON']]]
];
