#######################################
#      CXX Driver Config for MCI      #
#######################################

#######################################
#            Variables                #
#######################################
variables:

    ## source variables
    source:
        ubuntu_source: &ubuntu_source https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-latest.tgz
        osx_source: &osx_source https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-latest.tgz

    ## cmake path variables
    cmake_path:
        ubuntu_cmake_path: &ubuntu_cmake_path /opt/cmake/bin/cmake
        osx_cmake_path: &osx_cmake_path /Applications/Cmake.app/Contents/bin/cmake

    ## tar options variables
    tar_options:
        ubuntu_tar_options: &ubuntu_tar_options --wildcards --no-anchored

    ## cmake flag variables
    cmake_flags:
        ubuntu_cmake_flags: &ubuntu_cmake_flags -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wno-attributes -Werror -Wno-error=missing-field-initializers"
        ubuntu_boost_cmake_flags: &ubuntu_boost_cmake_flags -DBSONCXX_POLY_USE_BOOST=ON -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wno-attributes -Werror -Wno-error=missing-field-initializers"
        ubuntu_std_experimental_cmake_flags: &ubuntu_std_experimental_cmake_flags -DBSONCXX_POLY_USE_STD_EXPERIMENTAL=ON -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wno-attributes -Werror -Wno-error=missing-field-initializers"
        osx_cmake_flags: &osx_cmake_flags -DCMAKE_CXX_FLAGS="-stdlib=libc++ -Wall -Wextra -Wno-attributes -Werror -Wno-error=missing-field-initializers" -DBSONCXX_POLY_USE_BOOST=ON -DLIBBSON_DIR=/data/tmp/c-driver-install -DLIBMONGOC_DIR=/data/tmp/c-driver-install
        asan_cmake_flags: &asan_cmake_flags -DCMAKE_CXX_FLAGS="-fsanitize=address -O1 -fno-omit-frame-pointer -Wall -Wextra -Wno-attributes -Werror -Wno-error=missing-field-initializers -Wno-error=maybe-uninitialized"
        ubsan_cmake_flags: &ubsan_cmake_flags -DCMAKE_CXX_COMPILER="/usr/bin/clang++" -DCMAKE_CXX_FLAGS="-fsanitize=undefined -g -fno-omit-frame-pointer -fsanitize-blacklist=$(pwd)/../etc/ubsan.blacklist -fno-sanitize-recover -Wall -Wextra -Wno-attributes -Werror -Wno-error=missing-field-initializers"

    ## test parameters
    test_params:
        asan_test_params: &asan_test_params ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-3.5 ASAN_OPTIONS="detect_leaks=1"
        ubsan_test_params: &ubsan_test_params UBSAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer UBSAN_OPTIONS="print_stacktrace=1"


#######################################
#            Functions                #
#######################################

functions:
    "fetch_source":
        command: git.get_project
        params:
            directory: "mongo-cxx-driver"

    "start_mongod":
        command: shell.exec
        params:
            working_dir: "."
            script: |
                curl -o mongodb.tgz ${source}
                tar --extract --file mongodb.tgz --strip-components=2 ${tar_options} "*/bin/mongod"
                mkdir -p /data/tmp/db
                ./mongod --fork --logpath=/data/tmp/log --dbpath=/data/tmp/db --pidfilepath=/data/tmp/pid

    "install_c_driver":
        command: shell.exec
        params:
            working_dir: "."
            ## Use --disable-extra-align when configuring the C driver to avoid misalignment errors in UBSAN
            script: |
                git clone -b master https://github.com/mongodb/mongo-c-driver.git
                cd mongo-c-driver
                rm -rf /data/tmp/c-driver-install
                ./autogen.sh --prefix="/data/tmp/c-driver-install" --enable-tests=no --enable-examples=no --with-libbson=bundled --disable-extra-align
                make
                make install

    "stop_mongod":
        command: shell.exec
        params:
            working_dir: "."
            script:
               kill -TERM $(cat /data/tmp/pid)


#######################################
#              Pre Task               #
#######################################

pre:
  - command: expansions.fetch
    params:
      keys:
        - local_key: "aws_key"
          remote_key: "project_aws_key"
        - local_key: "aws_secret"
          remote_key: "project_aws_secret"
  - command: shell.exec
    params:
      script: |
        rm -rf "mongo-cxx-driver"
        rm -fr "mongo-c-driver"
        rm -fr mongod

#######################################
#               Tasks                 #
#######################################

tasks:
    - name: compile_and_test
      commands:
        - func: "fetch_source"
        - command: git.apply_patch
          params:
              directory: "mongo-cxx-driver"
        - func: "install_c_driver"
        - func: "start_mongod"
        - command: shell.exec
          params:
              working_dir: "mongo-cxx-driver/build"
              script: |
                  set -e
                  PKG_CONFIG_PATH="/data/tmp/c-driver-install/lib/pkgconfig" ${cmake_path} ${cmake_flags} -DCMAKE_BUILD_TYPE=${build_type} -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_C_FLAGS="-Wall -Wextra -Wno-attributes -Werror -Wno-error=missing-field-initializers" ..
                  make
                  ${test_params} ./src/bsoncxx/test/test_bson
                  ${test_params} ./src/mongocxx/test/test_driver
                  make run-examples
        - func: "stop_mongod"

#######################################
#           Buildvariants             #
#######################################

buildvariants:

    #######################################
    #         Linux Buildvariants         #
    #######################################
    - name: ubuntu1404-release
      display_name: "Ubuntu 14.04 Release"
      expansions:
          build_type: "Release"
          source: *ubuntu_source
          tar_options: *ubuntu_tar_options
          cmake_path: *ubuntu_cmake_path
          cmake_flags: *ubuntu_cmake_flags
      run_on:
          - ubuntu1404-test
      tasks:
          - name: compile_and_test

    - name: ubuntu1404-debug
      display_name: "Ubuntu 14.04 Debug"
      expansions:
          build_type: "Debug"
          source: *ubuntu_source
          tar_options: *ubuntu_tar_options
          cmake_path: *ubuntu_cmake_path
          cmake_flags: *ubuntu_cmake_flags
      run_on:
          - ubuntu1404-test
      tasks:
          - name: compile_and_test

    - name: ubuntu1404-debug-boost
      display_name: "Ubuntu 14.04 Debug with boost"
      expansions:
          build_type: "Debug"
          source: *ubuntu_source
          tar_options: *ubuntu_tar_options
          cmake_path: *ubuntu_cmake_path
          cmake_flags: *ubuntu_boost_cmake_flags
      run_on:
          - ubuntu1404-test
      tasks:
          - name: compile_and_test

    - name: ubuntu1404-debug-std-experimental
      display_name: "Ubuntu 14.04 Debug with std experimental"
      expansions:
          build_type: "Debug"
          source: *ubuntu_source
          tar_options: *ubuntu_tar_options
          cmake_path: *ubuntu_cmake_path
          cmake_flags: *ubuntu_std_experimental_cmake_flags
      run_on:
          - ubuntu1404-test
      tasks:
          - name: compile_and_test

    - name: osx-108
      display_name: "OS X 10.8 Release"
      expansions:
          build_type: "Release"
          source: *osx_source
          cmake_path: *osx_cmake_path
          cmake_flags: *osx_cmake_flags
      run_on:
          - osx-108
      tasks:
          - name: compile_and_test

    - name: ubuntu1410-debug-asan
      display_name: "ASAN Ubuntu 14.10 Debug"
      expansions:
          build_type: "Debug"
          source: *ubuntu_source
          tar_options: *ubuntu_tar_options
          cmake_path: *ubuntu_cmake_path
          cmake_flags: *asan_cmake_flags
          test_params: *asan_test_params
      run_on:
          - ubuntu1410-build
      tasks:
          - name: compile_and_test

    - name: ubuntu1410-debug-ubsan
      display_name: "UBSAN Ubuntu 14.10 Debug"
      expansions:
          build_type: "Debug"
          source: *ubuntu_source
          tar_options: *ubuntu_tar_options
          cmake_path: *ubuntu_cmake_path
          cmake_flags: *ubsan_cmake_flags
          test_params: *ubsan_test_params
      run_on:
          - ubuntu1410-build
      tasks:
          - name: compile_and_test
