exec_timeout_secs: 3600

command_type: system
stepback: true
pre_error_fails_task: true
post_error_fails_task: false

include:
  - filename: .evergreen/generated_configs/functions.yml
  - filename: .evergreen/generated_configs/tasks.yml
  - filename: .evergreen/generated_configs/task_groups.yml
  - filename: .evergreen/generated_configs/variants.yml

post:
    - func: "stop_mongod"
    - func: "backtrace"
    # Workaround for CXX-2040
    # - func: "upload working dir"
    - func: "upload mongo orchestration artifacts"
    - func: "upload code coverage"
