#######################################
#      CXX Driver Config for MCI      #
#######################################

exec_timeout_secs: 3600

include:
  - filename: .evergreen/generated_configs/functions.yml
  - filename: .evergreen/generated_configs/tasks.yml
  - filename: .evergreen/generated_configs/task_groups.yml
  - filename: .evergreen/generated_configs/variants.yml

#######################################
#              Post Task              #
#######################################

post:
    - func: "stop_mongod"
    - func: "backtrace"
    # Workaround for CXX-2040
    # - func: "upload working dir"
    - func: "upload mongo orchestration artifacts"
    - func: "upload code coverage"
