#######################################
#      CXX Driver Config for MCI      #
#######################################

#######################################
#            Functions                #
#######################################

functions:
    "fetch_source":
        command: git.get_project
        params:
            directory: "mongo-cxx-driver"

    "start_mongod":
        command: shell.exec
        params:
            working_dir: "."
            script: |
                wget -O mongodb.tgz https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-latest.tgz
                tar --extract --file mongodb.tgz --strip-components=2 --wildcards --no-anchored "*/bin/mongod"
                ./mongod --fork --logpath=/data/log --dbpath=/data/db --pidfilepath=/data/pid

    "install_c_driver":
        command: shell.exec
        params:
            working_dir: "."
            script: |
                git clone https://github.com/mongodb/mongo-c-driver.git
                cd mongo-c-driver
                rm -rf /data/c-driver-install
                ./autogen.sh --prefix="/data/c-driver-install" --enable-tests=no --enable-examples=no
                make
                make install

    "stop_mongod":
        command: shell.exec
        params:
            working_dir: "."
            script:
               kill -TERM $(cat /data/pid) 


#######################################
#              Pre Task               #
#######################################

pre:
  - command: expansions.fetch
    params:
      keys:
        - local_key: "aws_key"
          remote_key: "project_aws_key"
        - local_key: "aws_secret"
          remote_key: "project_aws_secret"
  - command: shell.exec
    params:
      script: |
        rm -rf "mongo-cxx-driver"
        rm -fr "mongo-c-driver"
        rm -fr mongod

#######################################
#               Tasks                 #
#######################################

tasks:
    - name: compile_and_test
      commands:
        - func: "fetch_source"
        - command: git.apply_patch
          params:
              directory: "mongo-cxx-driver"
        - func: "install_c_driver"
        - func: "start_mongod"
        - command: shell.exec
          params:
              working_dir: "mongo-cxx-driver/build"
              script: |
                  PKG_CONFIG_PATH="/data/c-driver-install/lib/pkgconfig" /opt/cmake-3.1.1-Linux-x86_64/bin/cmake -DBUILD_UNIT_TESTS=on -DCMAKE_BUILD_TYPE=${build_type} ..
                  make
                  make test
        - func: "stop_mongod"

#######################################
#           Buildvariants             #
#######################################

buildvariants:

    #######################################
    #         Linux Buildvariants         #
    #######################################
    - name: ubuntu1404-release
      display_name: "Ubuntu 14.04 Release"
      expansions:
          build_type: "Release"
      run_on:
          - ubuntu1404-test
      tasks:
          - name: compile_and_test

    - name: ubuntu1404-debug
      display_name: "Ubuntu 14.04 Debug"
      expansions:
          build_type: "Debug"
      run_on:
          - ubuntu1404-test
      tasks:
          - name: compile_and_test
