[project]
name = "mongo-cxx-driver"
version = "0.1.0"
description = "For development purposes only"
requires-python = ">=3.10"

[tool.uv]
dev-dependencies = [
    "beautifulsoup4>=4.0",
    "click>=6.0",
    "gitpython>=3.1",
    "jira>=3.1",
    "looseversion>=1.3",
    "packaging>=14.0",
    "pygithub>=2.0",
]
