name: "Clone and Configure CMake"
description: "Clones the repository and configures CMake to pull dependency source code for Endor Labs scan. Note this action modifies .gitignore locally to ensure Endor Labs scans dependency sources in build/_deps."
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        fetch-tags: true
        submodules: recursive

    - name: Configure CMake and fetch dependency sources
      shell: bash
      run: |
        cmake \
          -B build \
          -DBUILD_VERSION=0.0.0 \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_STANDARD=17 \
          -DENABLE_TESTS=OFF \
          -DBUILD_TESTING=OFF \
          -DCMAKE_DISABLE_FIND_PACKAGE_bson=TRUE \
          -DCMAKE_DISABLE_FIND_PACKAGE_mongoc=TRUE \
          -S .

    - name: Modify .gitignore locally for Endor Labs scan
      shell: bash
      run: |
        # prevent exclusion of build/_deps from endorctl scan
        echo "!_deps" >>.gitignore
        echo "!_deps/**" >>.gitignore
