var searchData=
[
  ['change_5fstream_690',['change_stream',['../classmongocxx_1_1v__noabi_1_1change__stream.html',1,'mongocxx::change_stream'],['../classmongocxx_1_1v__noabi_1_1change__stream.html',1,'mongocxx::v_noabi::change_stream'],['../classmongocxx_1_1v__noabi_1_1options_1_1change__stream.html',1,'mongocxx::v_noabi::options::change_stream']]],
  ['chunks_5fand_5fbytes_5foffset_691',['chunks_and_bytes_offset',['../structmongocxx_1_1v__noabi_1_1gridfs_1_1chunks__and__bytes__offset.html',1,'mongocxx::v_noabi::gridfs']]],
  ['client_692',['client',['../classmongocxx_1_1v__noabi_1_1client.html',1,'mongocxx::client'],['../classmongocxx_1_1v__noabi_1_1client.html',1,'mongocxx::v_noabi::client'],['../classmongocxx_1_1v__noabi_1_1options_1_1client.html',1,'mongocxx::v_noabi::options::client']]],
  ['client_5fencryption_693',['client_encryption',['../classmongocxx_1_1v__noabi_1_1client__encryption.html',1,'mongocxx::client_encryption'],['../classmongocxx_1_1v__noabi_1_1client__encryption.html',1,'mongocxx::v_noabi::client_encryption'],['../classmongocxx_1_1v__noabi_1_1options_1_1client__encryption.html',1,'mongocxx::v_noabi::options::client_encryption']]],
  ['client_5fsession_694',['client_session',['../classmongocxx_1_1v__noabi_1_1client__session.html',1,'mongocxx::client_session'],['../classmongocxx_1_1v__noabi_1_1client__session.html',1,'mongocxx::v_noabi::client_session'],['../classmongocxx_1_1v__noabi_1_1options_1_1client__session.html',1,'mongocxx::v_noabi::options::client_session']]],
  ['close_5farray_5ftype_695',['close_array_type',['../structbsoncxx_1_1v__noabi_1_1builder_1_1stream_1_1close__array__type.html',1,'bsoncxx::v_noabi::builder::stream']]],
  ['close_5fdocument_5ftype_696',['close_document_type',['../structbsoncxx_1_1v__noabi_1_1builder_1_1stream_1_1close__document__type.html',1,'bsoncxx::v_noabi::builder::stream']]],
  ['closed_5fcontext_697',['closed_context',['../structbsoncxx_1_1v__noabi_1_1builder_1_1stream_1_1closed__context.html',1,'bsoncxx::v_noabi::builder::stream']]],
  ['collection_698',['collection',['../classmongocxx_1_1v__noabi_1_1collection.html',1,'mongocxx::collection'],['../classmongocxx_1_1v__noabi_1_1collection.html',1,'mongocxx::v_noabi::collection']]],
  ['command_5ffailed_5fevent_699',['command_failed_event',['../classmongocxx_1_1v__noabi_1_1events_1_1command__failed__event.html',1,'mongocxx::v_noabi::events']]],
  ['command_5fstarted_5fevent_700',['command_started_event',['../classmongocxx_1_1v__noabi_1_1events_1_1command__started__event.html',1,'mongocxx::v_noabi::events']]],
  ['command_5fsucceeded_5fevent_701',['command_succeeded_event',['../classmongocxx_1_1v__noabi_1_1events_1_1command__succeeded__event.html',1,'mongocxx::v_noabi::events']]],
  ['concatenate_5farray_702',['concatenate_array',['../structbsoncxx_1_1v__noabi_1_1builder_1_1concatenate__array.html',1,'bsoncxx::v_noabi::builder']]],
  ['concatenate_5fdoc_703',['concatenate_doc',['../structbsoncxx_1_1v__noabi_1_1builder_1_1concatenate__doc.html',1,'bsoncxx::v_noabi::builder']]],
  ['const_5fiterator_704',['const_iterator',['../classbsoncxx_1_1v__noabi_1_1array_1_1view_1_1const__iterator.html',1,'bsoncxx::v_noabi::array::view::const_iterator'],['../classbsoncxx_1_1v__noabi_1_1document_1_1view_1_1const__iterator.html',1,'bsoncxx::v_noabi::document::view::const_iterator']]],
  ['core_705',['core',['../classbsoncxx_1_1v__noabi_1_1builder_1_1core.html',1,'bsoncxx::v_noabi::builder']]],
  ['count_706',['count',['../classmongocxx_1_1v__noabi_1_1options_1_1count.html',1,'mongocxx::v_noabi::options']]],
  ['create_5fcollection_5fdeprecated_707',['create_collection_deprecated',['../classmongocxx_1_1v__noabi_1_1options_1_1create__collection__deprecated.html',1,'mongocxx::v_noabi::options']]],
  ['cursor_708',['cursor',['../classmongocxx_1_1v__noabi_1_1cursor.html',1,'mongocxx::cursor'],['../classmongocxx_1_1v__noabi_1_1cursor.html',1,'mongocxx::v_noabi::cursor']]]
];
