var searchData=
[
  ['failure_0',['Failure',['../topic-bsoncxx-examples-bson-errors.html#basic-append-failure',1,'Basic Append Failure'],['../topic-bsoncxx-examples-bson-errors.html#basic-append-failure-1',1,'Basic Append Failure'],['../topic-bsoncxx-examples-bson-errors.html#sub-array-append-failure',1,'Sub-Array Append Failure'],['../topic-bsoncxx-examples-bson-errors.html#sub-array-append-failure-1',1,'Sub-Array Append Failure'],['../topic-bsoncxx-examples-bson-errors.html#sub-document-append-failure',1,'Sub-Document Append Failure'],['../topic-bsoncxx-examples-bson-errors.html#sub-document-append-failure-1',1,'Sub-Document Append Failure']]],
  ['find_1',['find',['../topic-bsoncxx-examples-bson-documents.html#using-find',1,'Using find()'],['../topic-bsoncxx-examples-bson-documents.html#using-find-1',1,'Using find()']]],
  ['find_20a_20document_2',['Find a Document',['../topic-mongocxx-examples-collections.html#find-a-document',1,'']]],
  ['find_20and_20delete_20a_20document_3',['Find and Delete a Document',['../topic-mongocxx-examples-collections.html#find-and-delete-a-document',1,'']]],
  ['find_20and_20replace_20a_20document_4',['Find and Replace a Document',['../topic-mongocxx-examples-collections.html#find-and-replace-a-document',1,'']]],
  ['find_20and_20update_20a_20document_5',['Find and Update a Document',['../topic-mongocxx-examples-collections.html#find-and-update-a-document',1,'']]],
  ['find_20distinct_20values_6',['Find Distinct Values',['../topic-mongocxx-examples-collections.html#find-distinct-values',1,'']]],
  ['find_20multiple_20documents_7',['Find Multiple Documents',['../topic-mongocxx-examples-collections.html#find-multiple-documents',1,'']]],
  ['for_20a_20single_20type_8',['For a Single Type',['../topic-bsoncxx-examples-bson-documents.html#for-a-single-type',1,'']]],
  ['for_20multiple_20types_9',['For Multiple Types',['../topic-bsoncxx-examples-bson-documents.html#for-multiple-types',1,'For Multiple Types'],['../topic-bsoncxx-examples-bson-documents.html#for-multiple-types-1',1,'For Multiple Types']]],
  ['for_20single_20type_10',['For Single Type',['../topic-bsoncxx-examples-bson-documents.html#for-single-type',1,'']]],
  ['from_20a_20bson_20type_11',['From a BSON Type',['../topic-bsoncxx-examples-bson-documents.html#from-a-bson-type',1,'']]],
  ['from_20a_20client_12',['From a Client',['../topic-mongocxx-examples-change-streams.html#from-a-client',1,'']]],
  ['from_20a_20collection_13',['From a Collection',['../topic-mongocxx-examples-change-streams.html#from-a-collection',1,'']]],
  ['from_20a_20database_14',['From a Database',['../topic-mongocxx-examples-change-streams.html#from-a-database',1,'']]],
  ['from_20a_20document_15',['From a Document',['../topic-bsoncxx-examples-bson-documents.html#from-a-document',1,'']]],
  ['from_20a_20document_20element_16',['From a Document Element',['../topic-bsoncxx-examples-bson-documents.html#from-a-document-element',1,'']]],
  ['from_20a_20json_20string_17',['From a JSON String',['../topic-bsoncxx-examples-bson-documents.html#from-a-json-string',1,'From a JSON String'],['../topic-bsoncxx-examples-bson-documents.html#from-a-json-string-1',1,'From a JSON String']]],
  ['from_20a_20value_20type_18',['From a Value Type',['../topic-bsoncxx-examples-bson-documents.html#from-a-value-type',1,'']]],
  ['from_20an_20array_19',['From an Array',['../topic-bsoncxx-examples-bson-documents.html#from-an-array',1,'']]],
  ['from_20an_20array_20element_20',['From an Array Element',['../topic-bsoncxx-examples-bson-documents.html#from-an-array-element',1,'']]],
  ['from_20an_20invalid_20bson_20array_21',['From an Invalid BSON Array',['../topic-bsoncxx-examples-bson-errors.html#from-an-invalid-bson-array',1,'']]],
  ['from_20an_20invalid_20bson_20document_22',['From an Invalid BSON Document',['../topic-bsoncxx-examples-bson-errors.html#from-an-invalid-bson-document',1,'']]],
  ['from_20an_20invalid_20element_23',['From an Invalid Element',['../topic-bsoncxx-examples-bson-errors.html#from-an-invalid-element',1,'']]],
  ['from_20an_20invalid_20json_20string_24',['From an Invalid JSON String',['../topic-bsoncxx-examples-bson-errors.html#from-an-invalid-json-string',1,'']]],
  ['from_20bytes_25',['From Bytes',['../topic-bsoncxx-examples-decimal128.html#from-bytes',1,'']]],
  ['from_20raw_20bytes_26',['From Raw Bytes',['../topic-bsoncxx-examples-bson-documents.html#from-raw-bytes',1,'From Raw Bytes'],['../topic-bsoncxx-examples-bson-documents.html#from-raw-bytes-1',1,'From Raw Bytes']]]
];
