var searchData=
[
  ['change_5fstream_634',['change_stream',['../classmongocxx_1_1change__stream.html',1,'mongocxx::change_stream'],['../classmongocxx_1_1options_1_1change__stream.html',1,'mongocxx::options::change_stream']]],
  ['client_635',['client',['../classmongocxx_1_1client.html',1,'mongocxx::client'],['../classmongocxx_1_1options_1_1client.html',1,'mongocxx::options::client']]],
  ['client_5fencryption_636',['client_encryption',['../classmongocxx_1_1client__encryption.html',1,'mongocxx::client_encryption'],['../classmongocxx_1_1options_1_1client__encryption.html',1,'mongocxx::options::client_encryption']]],
  ['client_5fsession_637',['client_session',['../classmongocxx_1_1client__session.html',1,'mongocxx::client_session'],['../classmongocxx_1_1options_1_1client__session.html',1,'mongocxx::options::client_session']]],
  ['close_5farray_5ftype_638',['close_array_type',['../structbsoncxx_1_1builder_1_1stream_1_1close__array__type.html',1,'bsoncxx::builder::stream']]],
  ['close_5fdocument_5ftype_639',['close_document_type',['../structbsoncxx_1_1builder_1_1stream_1_1close__document__type.html',1,'bsoncxx::builder::stream']]],
  ['closed_5fcontext_640',['closed_context',['../structbsoncxx_1_1builder_1_1stream_1_1closed__context.html',1,'bsoncxx::builder::stream']]],
  ['collection_641',['collection',['../classmongocxx_1_1collection.html',1,'mongocxx']]],
  ['command_5ffailed_5fevent_642',['command_failed_event',['../classmongocxx_1_1events_1_1command__failed__event.html',1,'mongocxx::events']]],
  ['command_5fstarted_5fevent_643',['command_started_event',['../classmongocxx_1_1events_1_1command__started__event.html',1,'mongocxx::events']]],
  ['command_5fsucceeded_5fevent_644',['command_succeeded_event',['../classmongocxx_1_1events_1_1command__succeeded__event.html',1,'mongocxx::events']]],
  ['concatenate_5farray_645',['concatenate_array',['../structbsoncxx_1_1builder_1_1concatenate__array.html',1,'bsoncxx::builder']]],
  ['concatenate_5fdoc_646',['concatenate_doc',['../structbsoncxx_1_1builder_1_1concatenate__doc.html',1,'bsoncxx::builder']]],
  ['const_5fiterator_647',['const_iterator',['../classbsoncxx_1_1array_1_1view_1_1const__iterator.html',1,'bsoncxx::array::view::const_iterator'],['../classbsoncxx_1_1document_1_1view_1_1const__iterator.html',1,'bsoncxx::document::view::const_iterator']]],
  ['core_648',['core',['../classbsoncxx_1_1builder_1_1core.html',1,'bsoncxx::builder']]],
  ['count_649',['count',['../classmongocxx_1_1options_1_1count.html',1,'mongocxx::options']]],
  ['create_5fcollection_5fdeprecated_650',['create_collection_deprecated',['../classmongocxx_1_1options_1_1create__collection__deprecated.html',1,'mongocxx::options']]],
  ['cursor_651',['cursor',['../classmongocxx_1_1cursor.html',1,'mongocxx']]]
];
