var searchData=
[
  ['change_5fstream',['change_stream',['../classmongocxx_1_1options_1_1change__stream.html',1,'mongocxx::options::change_stream'],['../classmongocxx_1_1change__stream.html',1,'mongocxx::change_stream']]],
  ['client',['client',['../classmongocxx_1_1options_1_1client.html',1,'mongocxx::options::client'],['../classmongocxx_1_1client.html',1,'mongocxx::client']]],
  ['client_5fsession',['client_session',['../classmongocxx_1_1client__session.html',1,'mongocxx::client_session'],['../classmongocxx_1_1options_1_1client__session.html',1,'mongocxx::options::client_session']]],
  ['close_5farray_5ftype',['close_array_type',['../structbsoncxx_1_1builder_1_1stream_1_1close__array__type.html',1,'bsoncxx::builder::stream']]],
  ['close_5fdocument_5ftype',['close_document_type',['../structbsoncxx_1_1builder_1_1stream_1_1close__document__type.html',1,'bsoncxx::builder::stream']]],
  ['closed_5fcontext',['closed_context',['../structbsoncxx_1_1builder_1_1stream_1_1closed__context.html',1,'bsoncxx::builder::stream']]],
  ['collection',['collection',['../classmongocxx_1_1collection.html',1,'mongocxx']]],
  ['command_5ffailed_5fevent',['command_failed_event',['../classmongocxx_1_1events_1_1command__failed__event.html',1,'mongocxx::events']]],
  ['command_5fstarted_5fevent',['command_started_event',['../classmongocxx_1_1events_1_1command__started__event.html',1,'mongocxx::events']]],
  ['command_5fsucceeded_5fevent',['command_succeeded_event',['../classmongocxx_1_1events_1_1command__succeeded__event.html',1,'mongocxx::events']]],
  ['concatenate_5farray',['concatenate_array',['../structbsoncxx_1_1builder_1_1concatenate__array.html',1,'bsoncxx::builder']]],
  ['concatenate_5fdoc',['concatenate_doc',['../structbsoncxx_1_1builder_1_1concatenate__doc.html',1,'bsoncxx::builder']]],
  ['const_5fiterator',['const_iterator',['../classbsoncxx_1_1array_1_1view_1_1const__iterator.html',1,'bsoncxx::array::view::const_iterator'],['../classbsoncxx_1_1document_1_1view_1_1const__iterator.html',1,'bsoncxx::document::view::const_iterator']]],
  ['core',['core',['../classbsoncxx_1_1builder_1_1core.html',1,'bsoncxx::builder']]],
  ['count',['count',['../classmongocxx_1_1options_1_1count.html',1,'mongocxx::options']]],
  ['create_5fcollection',['create_collection',['../classmongocxx_1_1options_1_1create__collection.html',1,'mongocxx::options']]],
  ['create_5fview',['create_view',['../classmongocxx_1_1options_1_1create__view.html',1,'mongocxx::options']]],
  ['cursor',['cursor',['../classmongocxx_1_1cursor.html',1,'mongocxx']]]
];
