var searchData=
[
  ['change_5fstream_577',['change_stream',['../classmongocxx_1_1change__stream.html',1,'mongocxx::change_stream'],['../classmongocxx_1_1options_1_1change__stream.html',1,'mongocxx::options::change_stream']]],
  ['client_578',['client',['../classmongocxx_1_1client.html',1,'mongocxx::client'],['../classmongocxx_1_1options_1_1client.html',1,'mongocxx::options::client']]],
  ['client_5fsession_579',['client_session',['../classmongocxx_1_1client__session.html',1,'mongocxx::client_session'],['../classmongocxx_1_1options_1_1client__session.html',1,'mongocxx::options::client_session']]],
  ['close_5farray_5ftype_580',['close_array_type',['../structbsoncxx_1_1builder_1_1stream_1_1close__array__type.html',1,'bsoncxx::builder::stream']]],
  ['close_5fdocument_5ftype_581',['close_document_type',['../structbsoncxx_1_1builder_1_1stream_1_1close__document__type.html',1,'bsoncxx::builder::stream']]],
  ['closed_5fcontext_582',['closed_context',['../structbsoncxx_1_1builder_1_1stream_1_1closed__context.html',1,'bsoncxx::builder::stream']]],
  ['collection_583',['collection',['../classmongocxx_1_1collection.html',1,'mongocxx']]],
  ['command_5ffailed_5fevent_584',['command_failed_event',['../classmongocxx_1_1events_1_1command__failed__event.html',1,'mongocxx::events']]],
  ['command_5fstarted_5fevent_585',['command_started_event',['../classmongocxx_1_1events_1_1command__started__event.html',1,'mongocxx::events']]],
  ['command_5fsucceeded_5fevent_586',['command_succeeded_event',['../classmongocxx_1_1events_1_1command__succeeded__event.html',1,'mongocxx::events']]],
  ['concatenate_5farray_587',['concatenate_array',['../structbsoncxx_1_1builder_1_1concatenate__array.html',1,'bsoncxx::builder']]],
  ['concatenate_5fdoc_588',['concatenate_doc',['../structbsoncxx_1_1builder_1_1concatenate__doc.html',1,'bsoncxx::builder']]],
  ['const_5fiterator_589',['const_iterator',['../classbsoncxx_1_1array_1_1view_1_1const__iterator.html',1,'bsoncxx::array::view::const_iterator'],['../classbsoncxx_1_1document_1_1view_1_1const__iterator.html',1,'bsoncxx::document::view::const_iterator']]],
  ['core_590',['core',['../classbsoncxx_1_1builder_1_1core.html',1,'bsoncxx::builder']]],
  ['count_591',['count',['../classmongocxx_1_1options_1_1count.html',1,'mongocxx::options']]],
  ['create_5fcollection_592',['create_collection',['../classmongocxx_1_1options_1_1create__collection.html',1,'mongocxx::options']]],
  ['create_5fview_593',['create_view',['../classmongocxx_1_1options_1_1create__view.html',1,'mongocxx::options']]],
  ['cursor_594',['cursor',['../classmongocxx_1_1cursor.html',1,'mongocxx']]]
];
