MONGOCXX_VERSION={{ mongocxx_version }}
DOCKER=docker

.PHONY: build
build:
	$(DOCKER) build . \
		-t mongo-cxx-driver:$(MONGOCXX_VERSION)-{{ distro }}

.PHONY: nocachebuild
nocachebuild:
	$(DOCKER) build . \
		--no-cache \
		-t mongo-cxx-driver:$(MONGOCXX_VERSION)-{{ distro }}

.PHONY: run
run:
	$(DOCKER) run --rm -it mongo-cxx-driver:$(MONGOCXX_VERSION)-{{ distro }}

.PHONY: test
test:
	$(DOCKER) build . --no-cache -f TestDockerfile -t test-mongocxx-driver-image:$(MONGOCXX_VERSION)-{{ distro }}
	$(DOCKER) run test-mongocxx-driver-image:$(MONGOCXX_VERSION)-{{ distro }}

