
#ifndef MONGOCXX_API_H
#define MONGOCXX_API_H

#define MONGOCXX_API
#define MONGOCXX_PRIVATE
#define MONGOCXX_DEPRECATED [[deprecated]]
#define MONGOCXX_DEPRECATED_EXPORT
#define MONGOCXX_DEPRECATED_NO_EXPORT

#endif /* MONGOCXX_API_H */
