
#ifndef BSONCXX_API_H
#define BSONCXX_API_H

#define BSONCXX_API
#define BSONCXX_PRIVATE
#define BSONCXX_DEPRECATED [[deprecated]]
#define BSONCXX_DEPRECATED_EXPORT
#define BSONCXX_DEPRECATED_NO_EXPORT
#define DEFINE_NO_DEPRECATED

#endif /* BSONCXX_API_H */
