var searchData=
[
  ['in_20a_20document_0',['In a Document',['../topic-bsoncxx-examples-bson-documents.html#in-a-document',1,'In a Document'],['../topic-bsoncxx-examples-bson-errors.html#in-a-document-1',1,'In a Document']]],
  ['in_20an_20array_1',['In an Array',['../topic-bsoncxx-examples-bson-documents.html#in-an-array',1,'In an Array'],['../topic-bsoncxx-examples-bson-errors.html#in-an-array-1',1,'In an Array']]],
  ['in_20the_20database_2',['in the Database',['../topic-mongocxx-examples-databases.html#list-collection-names-in-the-database',1,'List Collection Names in the Database'],['../topic-mongocxx-examples-databases.html#list-collections-in-the-database',1,'List Collections in the Database']]],
  ['incompatible_20options_3',['Incompatible Options',['../topic-mongocxx-examples-collections.html#incompatible-options',1,'']]],
  ['index_4',['Index',['../topic-mongocxx-examples-collections.html#create-an-index',1,'Create an Index'],['../topic-mongocxx-examples-collections.html#create-an-index-1',1,'Create an Index'],['../topic-mongocxx-examples-collections.html#drop-an-index',1,'Drop an Index']]],
  ['index_20operations_5',['Index Operations',['../topic-mongocxx-examples-collections.html#index-operations',1,'']]],
  ['index_20view_6',['Index View',['../topic-mongocxx-examples-collections.html#obtain-an-index-view',1,'Obtain an Index View'],['../topic-mongocxx-examples-collections.html#with-an-index-view',1,'With an Index View']]],
  ['index_20with_20options_7',['Index With Options',['../topic-mongocxx-examples-collections.html#create-an-index-with-options',1,'Create an Index With Options'],['../topic-mongocxx-examples-collections.html#create-an-index-with-options-1',1,'Create an Index With Options']]],
  ['indexes_8',['Indexes',['../topic-mongocxx-examples-collections.html#create-multiple-indexes',1,'Create Multiple Indexes'],['../topic-mongocxx-examples-collections.html#drop-all-indexes',1,'Drop All Indexes'],['../topic-mongocxx-examples-collections.html#list-indexes',1,'List Indexes'],['../topic-mongocxx-examples-collections.html#list-indexes-1',1,'List Indexes']]],
  ['initialize_20the_20c_20driver_9',['Initialize the C++ Driver',['../topic-mongocxx-examples-instance.html#initialize-the-c-driver',1,'']]],
  ['insert_20a_20document_10',['Insert a Document',['../topic-mongocxx-examples-collections.html#insert-a-document',1,'']]],
  ['insert_20many_20documents_11',['Insert Many Documents',['../topic-mongocxx-examples-collections.html#insert-many-documents',1,'']]],
  ['instance_12',['Instance',['../topic-mongocxx-examples-instance.html#destroyed-instance',1,'Destroyed Instance'],['../topic-mongocxx-examples-instance.html',1,'Instance']]],
  ['instance_20recreation_13',['Instance Recreation',['../topic-mongocxx-examples-instance.html#instance-recreation',1,'']]],
  ['invalid_20auto_20encryption_20options_14',['Invalid Auto Encryption Options',['../topic-mongocxx-examples-clients.html#invalid-auto-encryption-options',1,'']]],
  ['invalid_20bson_20array_15',['From an Invalid BSON Array',['../topic-bsoncxx-examples-bson-errors.html#from-an-invalid-bson-array',1,'']]],
  ['invalid_20bson_20arrays_16',['Invalid BSON Arrays',['../topic-bsoncxx-examples-bson-errors.html#invalid-bson-arrays',1,'']]],
  ['invalid_20bson_20document_17',['From an Invalid BSON Document',['../topic-bsoncxx-examples-bson-errors.html#from-an-invalid-bson-document',1,'']]],
  ['invalid_20bson_20documents_18',['Invalid BSON Documents',['../topic-bsoncxx-examples-bson-errors.html#invalid-bson-documents',1,'']]],
  ['invalid_20client_19',['Invalid Client',['../topic-mongocxx-examples-clients.html#invalid-client',1,'']]],
  ['invalid_20collection_20',['Invalid Collection',['../topic-mongocxx-examples-collections.html#invalid-collection',1,'']]],
  ['invalid_20database_21',['Invalid Database',['../topic-mongocxx-examples-databases.html#invalid-database',1,'']]],
  ['invalid_20element_22',['Invalid Element',['../topic-bsoncxx-examples-bson-errors.html#from-an-invalid-element',1,'From an Invalid Element'],['../topic-bsoncxx-examples-bson-errors.html#invalid-element',1,'Invalid Element'],['../topic-bsoncxx-examples-bson-errors.html#invalid-element-1',1,'Invalid Element']]],
  ['invalid_20json_20string_23',['From an Invalid JSON String',['../topic-bsoncxx-examples-bson-errors.html#from-an-invalid-json-string',1,'']]],
  ['invalid_20parameter_24',['Invalid Parameter',['../topic-mongocxx-examples-collections.html#invalid-parameter',1,'']]],
  ['invalid_20stable_20api_20options_25',['Invalid Stable API Options',['../topic-mongocxx-examples-clients.html#invalid-stable-api-options',1,'']]],
  ['invalid_20type_26',['Invalid Type',['../topic-bsoncxx-examples-bson-errors.html#invalid-type',1,'Invalid Type'],['../topic-bsoncxx-examples-bson-errors.html#invalid-type-1',1,'Invalid Type'],['../topic-bsoncxx-examples-bson-errors.html#query-an-invalid-type',1,'Query an Invalid Type']]],
  ['invalid_20uri_27',['Invalid URI',['../topic-mongocxx-examples-uri.html#invalid-uri',1,'']]],
  ['invalid_20value_28',['Create an Invalid Value',['../topic-bsoncxx-examples-bson-errors.html#create-an-invalid-value',1,'']]],
  ['issues_29',['Bugs and issues',['../index.html#bugs-and-issues',1,'']]],
  ['iteration_30',['Iteration',['../topic-bsoncxx-examples-bson-documents.html#by-iteration',1,'By Iteration'],['../topic-bsoncxx-examples-bson-documents.html#by-iteration-1',1,'By Iteration'],['../topic-bsoncxx-examples-bson-errors.html#by-iteration-2',1,'By Iteration'],['../topic-bsoncxx-examples-bson-errors.html#by-iteration-3',1,'By Iteration']]],
  ['iterators_31',['Iterators',['../topic-bsoncxx-examples-bson-errors.html#end-iterators',1,'End Iterators'],['../topic-bsoncxx-examples-bson-errors.html#end-iterators-1',1,'End Iterators'],['../topic-bsoncxx-examples-bson-documents.html#using-iterators',1,'Using Iterators'],['../topic-bsoncxx-examples-bson-documents.html#using-iterators-1',1,'Using Iterators']]]
];
