var searchData=
[
  ['oid_0',['oid',['../classbsoncxx_1_1oid.html',1,'bsoncxx::oid'],['../classbsoncxx_1_1v__noabi_1_1oid.html',1,'bsoncxx::v_noabi::oid']]],
  ['open_5farray_5ftype_1',['open_array_type',['../structbsoncxx_1_1v__noabi_1_1builder_1_1stream_1_1open__array__type.html',1,'bsoncxx::v_noabi::builder::stream']]],
  ['open_5fdocument_5ftype_2',['open_document_type',['../structbsoncxx_1_1v__noabi_1_1builder_1_1stream_1_1open__document__type.html',1,'bsoncxx::v_noabi::builder::stream']]],
  ['operation_5fexception_3',['operation_exception',['../classmongocxx_1_1operation__exception.html',1,'mongocxx::operation_exception'],['../classmongocxx_1_1v__noabi_1_1operation__exception.html',1,'mongocxx::v_noabi::operation_exception']]],
  ['optional_4',['optional',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20bool_20_3e_5',['optional&lt; bool &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20bsoncxx_3a_3av_5fnoabi_3a_3adocument_3a_3avalue_20_3e_6',['optional&lt; bsoncxx::v_noabi::document::value &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20bsoncxx_3a_3av_5fnoabi_3a_3adocument_3a_3aview_20_3e_7',['optional&lt; bsoncxx::v_noabi::document::view &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20bsoncxx_3a_3av_5fnoabi_3a_3astdx_3a_3astring_5fview_20_3e_8',['optional&lt; bsoncxx::v_noabi::stdx::string_view &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20bsoncxx_3a_3av_5fnoabi_3a_3astring_3a_3aview_5for_5fvalue_20_3e_9',['optional&lt; bsoncxx::v_noabi::string::view_or_value &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20bsoncxx_3a_3av_5fnoabi_3a_3aview_5for_5fvalue_20_3e_10',['optional&lt; bsoncxx::v_noabi::view_or_value &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20bsoncxx_3a_3av_5fnoabi_3a_3aview_5for_5fvalue_3c_20view_2c_20value_20_3e_20_3e_11',['optional&lt; bsoncxx::v_noabi::view_or_value&lt; view, value &gt; &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20cursor_3a_3atype_20_3e_12',['optional&lt; cursor::type &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20double_20_3e_13',['optional&lt; double &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20encryption_5falgorithm_20_3e_14',['optional&lt; encryption_algorithm &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20encryption_5fquery_5ftype_20_3e_15',['optional&lt; encryption_query_type &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20int64_5ft_20_3e_16',['optional&lt; int64_t &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20key_5fmaterial_5ftype_20_3e_17',['optional&lt; key_material_type &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3aclient_20_2a_20_3e_18',['optional&lt; mongocxx::v_noabi::client * &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3ahint_20_3e_19',['optional&lt; mongocxx::v_noabi::hint &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3aoptions_3a_3aapm_20_3e_20',['optional&lt; mongocxx::v_noabi::options::apm &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3aoptions_3a_3aauto_5fencryption_20_3e_21',['optional&lt; mongocxx::v_noabi::options::auto_encryption &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3aoptions_3a_3arange_20_3e_22',['optional&lt; mongocxx::v_noabi::options::range &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3aoptions_3a_3areturn_5fdocument_20_3e_23',['optional&lt; mongocxx::v_noabi::options::return_document &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3aoptions_3a_3aserver_5fapi_20_3e_24',['optional&lt; mongocxx::v_noabi::options::server_api &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3aoptions_3a_3atls_20_3e_25',['optional&lt; mongocxx::v_noabi::options::tls &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3aoptions_3a_3atransaction_20_3e_26',['optional&lt; mongocxx::v_noabi::options::transaction &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3apool_20_2a_20_3e_27',['optional&lt; mongocxx::v_noabi::pool * &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3aread_5fconcern_20_3e_28',['optional&lt; mongocxx::v_noabi::read_concern &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3aread_5fpreference_20_3e_29',['optional&lt; mongocxx::v_noabi::read_preference &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3aresult_3a_3abulk_5fwrite_20_3e_30',['optional&lt; mongocxx::v_noabi::result::bulk_write &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3avalidation_5fcriteria_20_3e_31',['optional&lt; mongocxx::v_noabi::validation_criteria &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20mongocxx_3a_3av_5fnoabi_3a_3awrite_5fconcern_20_3e_32',['optional&lt; mongocxx::v_noabi::write_concern &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20ns_5fpair_20_3e_33',['optional&lt; ns_pair &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20std_3a_3achrono_3a_3amilliseconds_20_3e_34',['optional&lt; std::chrono::milliseconds &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20std_3a_3achrono_3a_3aseconds_20_3e_35',['optional&lt; std::chrono::seconds &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20std_3a_3aint32_5ft_20_3e_36',['optional&lt; std::int32_t &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20std_3a_3aint64_5ft_20_3e_37',['optional&lt; std::int64_t &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20std_3a_3astring_20_3e_38',['optional&lt; std::string &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20std_3a_3auint8_5ft_20_3e_39',['optional&lt; std::uint8_t &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20v_5fnoabi_3a_3adocument_3a_3avalue_20_3e_40',['optional&lt; v_noabi::document::value &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20validation_5faction_20_3e_41',['optional&lt; validation_action &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20validation_5flevel_20_3e_42',['optional&lt; validation_level &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20value_20_3e_43',['optional&lt; Value &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]],
  ['optional_3c_20value_20_3e_44',['optional&lt; value &gt;',['../classbsoncxx_1_1v__noabi_1_1stdx_1_1optional.html',1,'bsoncxx::v_noabi::stdx']]]
];
