# -*- mode: python; -*-
#
# This is the principle SConscript file, invoked by the SConstruct.  Its job is
# to delegate to any and all per-module SConscript files.
Import('env')

env.SConscript('third_party/SConscript')
env.SConscript('SConscript.client')
env.SConscript('mongo/SConscript')
